# Use an official image of Node.js runtime
FROM node:22-alpine

# Set the work dir inside the container
WORKDIR /app

# Copy all the pacjage.json file in the work dir
COPY package*.json .

# install the dependency
RUN npm install

COPY  . .

ENV PORT=3000

CMD ["node", "index.js"]